language: bash
services: docker
sudo: required

notifications:
  email: false
  slack:
    rooms:
      - secure: XuTZywMCIEVU/IxZh/6By/EtJNbqCBoB6BYGu7vqt4j/28rlW+xNjRPnAcjR+WH2RtjBGVXJjRlbpRcbOmdyW1341CQBl6vKeElWDrXST0ChRQiHgVUrJyaPtjeMYHIUBUiG61O4wm+ZpiicDR4gByK4dXfsx8vyfMgoTATss9R0L/8Zl2iZvqsYIXB2Pp7VppcGhwroaxNi3WSEnntDqupCUFQ8hQL4EDH9MwbbfHivWnbaekMGaxiE+TDGJLWqi8tSbSSLzX24U/LuhgPzCsSC4yOot11T0W4VWsdukV8znNoLulsWvZ1ho3WcnEJkS4/71N4IJILq115iSTZonJBqPCtu5+mGKi+98TJlXSoeutP2OKlvy6RVx5yEhf/i5Mftw6MTtznmSB9fPr8X/IpcTj7H4NFvZYZ7JMesttpGjfCWtNQYRgOY9La1H1QEfrqaDQdOHkORyx5VF4HN1DOHOGxE+9Lj3v9UR5/dg/8U4iyz0AqitHFGoi5p2p2lId+qIfEN2LnLiBAejXbQNclvZFZWBD7J2OoaCZc5LkaBaiRl5YQlfPqNMmOHoT9Ygllzwtd0cnpALB9LQqZXNG23At5DKWyGiMn/rOJrzWyZX4jAKYYjgokRQrS1fS2/JNUV2cdc3rsVSpbqOU+WfMIUbIq4jotsfzJXlYl/UGk=
    on_success: change

arch:
  - arm64
os: linux

env:
#  - SOURCE_GIT=https://github.com/kylemanna/docker-openvpn BASE_IMAGE=arm32v6/alpine:latest DEST_IMAGE=napnap75/rpi-openvpn
#  - SOURCE_GIT=https://github.com/atmoz/sftp GIT_BRANCH=alpine BASE_IMAGE=arm32v6/alpine:3.6 DEST_IMAGE=napnap75/rpi-sftpd IMAGE_TAG=alpine
#  - SOURCE_GIT=https://github.com/panubo/docker-sshd BASE_IMAGE=arm32v6/alpine:latest DEST_IMAGE=napnap75/rpi-sshd IMAGE_TAG=alpine
#  - SOURCE_GIT=https://github.com/instrumentisto/coturn-docker-image BASE_IMAGE=arm32v6/alpine:latest DEST_IMAGE=napnap75/rpi-coturn
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=core/nginx DEST_IMAGE=napnap75/mailu IMAGE_TAG=nginx BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=core/dovecot DEST_IMAGE=napnap75/mailu IMAGE_TAG=dovecot BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=core/postfix DEST_IMAGE=napnap75/mailu IMAGE_TAG=postfix BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=core/rspamd DEST_IMAGE=napnap75/mailu IMAGE_TAG=rspamd BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=optional/clamav DEST_IMAGE=napnap75/mailu IMAGE_TAG=clamav BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=optional/traefik-certdumper BASE_IMAGE=ldez/traefik-certs-dumper:latest-arm.v6 DEST_IMAGE=napnap75/mailu IMAGE_TAG=traefik-certdumper
#  - SOURCE_GIT=https://github.com/Mailu/Mailu SUB_DIRECTORY=core/admin DEST_IMAGE=napnap75/mailu IMAGE_TAG=admin BUILD_OPTIONS="--build-arg ARCH=arm32v7/ --build-arg DISTRO=balenalib/rpi-alpine:3.10 --build-arg QEMU=arm"
  
script:
  - mkdir source
  - if [ "$GIT_BRANCH" == "" ]; then
      git clone ${SOURCE_GIT} source ;
    else
      git clone -b ${GIT_BRANCH} ${SOURCE_GIT} source ;
    fi
  - cd source
  - if [ "$SUB_DIRECTORY" != "" ]; then
      cd $SUB_DIRECTORY ;
    fi
  - if [ "$DOCKERFILE_FILE" != "" ]; then
      mv "$DOCKERFILE_FILE" Dockerfile ;
    fi
  - if [ "$BASE_IMAGE" != "" ]; then
      sed -i "s#FROM .*#FROM ${BASE_IMAGE}#" Dockerfile ;
    fi
  - if [ "$SED_COMMAND" != "" ]; then
      sed -i "$SED_COMMAND" Dockerfile ;
    fi
  - cat Dockerfile
  - if [ "$IMAGE_TAG" == "" ]; then
      docker build $BUILD_OPTIONS -t ${DEST_IMAGE}:latest . ;
    else
      docker build $BUILD_OPTIONS -t ${DEST_IMAGE}:${IMAGE_TAG} . ;
    fi
    
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$IMAGE_TAG" == "" ]; then
      docker push ${DEST_IMAGE}:latest ;
    else
      docker push ${DEST_IMAGE}:${IMAGE_TAG} ;
    fi
    
