language: bash
services: docker
sudo: required

env:
  - SOURCE_GIT=https://github.com/kylemanna/docker-openvpn BASE_IMAGE=arm32v6/alpine:latest ADD_QEMU=true DEST_IMAGE=napnap75/rpi-openvpn
  - SOURCE_GIT=https://github.com/atmoz/sftp GIT_BRANCH=alpine BASE_IMAGE=arm32v6/alpine:3.6 ADD_QEMU=true DEST_IMAGE=napnap75/rpi-sftpd IMAGE_TAG=alpine
  
install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  
script:
  - mkdir source
  - if [ "$GIT_BRANCH" == "" ]; then
      git clone ${SOURCE_GIT} source ;
    else
      git clone -b ${GIT_BRANCH} ${SOURCE_GIT} source ;
    fi
  - cd source
  - if [ "$BASE_IMAGE" != "" ]; then
      sed -i "s#FROM .*#FROM ${BASE_IMAGE}#" Dockerfile ;
    fi
  - if [ "$ADD_QEMU" != "" ]; then
      curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz && tar zx -f qemu-arm-static.tar.gz ;
      sed -i "/FROM .*/a ADD qemu-arm-static /usr/bin" Dockerfile ;
    fi
  - cat Dockerfile
  - if [ "$IMAGE_TAG" == "" ]; then
      docker build -t ${DEST_IMAGE}:latest . ;
    else
      docker build -t ${DEST_IMAGE}:${IMAGE_TAG} . ;
    fi
    
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      if [ "$IMAGE_TAG" == "" ]; then
        docker push ${DEST_IMAGE}:latest ;
      else
        docker push ${DEST_IMAGE}:${IMAGE_TAG} ;
      fi ;
    fi
